# Generated by Django 3.2.7 on 2022-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
